info:
  contact: {}
  license: {}
paths:
  /v1/stores/{id}/courses/{course_id}:
    get:
      consumes:
      - application/json
      description: 获取课程基础信息
      parameters:
      - description: Bearer
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"error_code":0,"data":{},"message":"ok"}'
          schema:
            type: string
        "400":
          description: '{"error_code":400,"message":"ok","errors":{}}'
          schema:
            type: string
        "500":
          description: '{"error_code":500,"message":"something wrong"}'
          schema:
            type: string
      summary: 获取课程基础信息
      tags:
      - courses
swagger: "2.0"
